data:
    dataset: "Synthsis"
    image_size: 64
    channels: 1
    num_workers: 32
    data_dir: "scratch/"
    conditional: True

model:
    in_channels: 1
    out_ch: 1
    out_channels: 2 # added
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 2
    n_epochs: 1000
    n_iters: 200
    snapshot_freq: 1000
    validation_freq: 100

sampling:
    batch_size: 2
    last_only: True
    sample_type: "generalized" # added
    schedule: "linear" # added

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001